### ISSUE TITLE
Can you tell me about the installation environment? I have an installation error

### ISSUE THREAD

**Issue by laitianwen** [AppleBotzz/ComfyUI_LLMVISION#1]
Anthropic Loaded
Traceback (most recent call last):
  File "E:\sd\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\sd\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LLMVISION\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\sd\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LLMVISION\nodes.py", line 6, in <module>
    import anthropic
  File "C:\Users\82407\AppData\Local\Programs\Python\Python311\Lib\site-packages\anthropic\__init__.py", line 88, in <module>
    boot_test()
  File "C:\Users\82407\AppData\Local\Programs\Python\Python311\Lib\site-packages\anthropic\_anter.py", line 119, in boot_test
    status = verify_status()
             ^^^^^^^^^^^^^^^
  File "C:\Users\82407\AppData\Local\Programs\Python\Python311\Lib\site-packages\anthropic\_syscheck.py", line 42, in verify_status
    "processor_brand": cpuinfo.get_cpu_info()['brand_raw'],
                       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'brand_raw'

Cannot import E:\sd\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LLMVISION module for custom nodes: 'brand_raw'

**Comment by AppleBotzz** [comment]
Welcome to the fun that is the anthropic/openai sdk, I had to make a custom wheel to fix bugs like this in their autogeneratred garbage.

Could you tell me a bit more about your system setup?

**Comment by AppleBotzz** [comment]
I just pushed updates to the custom whl files used in the requirements.txt, pull em and see if that fixes your issue
